apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak
  namespace: production
  labels:
    app: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
  strategy: {}
  template:
    metadata:
      labels:
        app: teamspeak
    spec:
      containers:
      - image: teamspeak:3.13
        name: teamspeak
        env:
         - name: TS3SERVER_LICENSE
           value: "accept"
        ports:
         - containerPort: 9987
           protocol: UDP

        volumeMounts:
         - name: teamspeak-data
           mountPath: /var/ts3server
        resources: {}
      volumes:
        - name: teamspeak-data
          persistentVolumeClaim:
            claimName: teamspeak-data
status: {}
