apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamspeak-data
  namespace: production

spec:
  storageClassName: teamspeak-local

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
